version: 2

release:
  draft: true

builds:
  - id: build
    main: ./src/.
    binary: cosmos
    ldflags: -s -w
    flags: -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      
